/**
 * Editor.tsx — CodeMirror 6 integration for Solid
 *
 * Design decisions encoded here:
 *
 *   1. CodeMirror owns the document. Solid's reactivity does not manage the
 *      editor content — only the note-switching signal. This is intentional:
 *      CM6's internal transaction model is superior to VDOM diffing for a
 *      high-frequency write surface.
 *
 *   2. 400ms debounced save. Immediate: dirty indicator. Deferred: localStorage.
 *      The split communicates to the user that their typing is tracked (dot
 *      appears instantly) without hammering localStorage on every keystroke.
 *
 *   3. Note switching uses a CSS opacity crossfade (120ms), not a JS animation.
 *      CSS transitions are composited by the browser without layout recalc;
 *      JS animations at this granularity would cause frame drops.
 *
 *   4. History is cleared on note switch. Cmd+Z must not cross note boundaries —
 *      that would be a shocking and destructive surprise for the user.
 *
 *   5. The "title extraction" heuristic: the first line of the document is used
 *      as the note title in the sidebar, stripping leading # characters.
 *      This aligns with how writers naturally structure a markdown document.
 */
import {
  onMount,
  onCleanup,
  createEffect,
  createSignal,
  type JSX,
} from 'solid-js';
import { EditorView, basicSetup }       from 'codemirror';
import { EditorState, EditorSelection } from '@codemirror/state';
import { markdown, markdownLanguage }   from '@codemirror/lang-markdown';
import { languages }                    from '@codemirror/language-data';
import { store, applyNoteSave }         from './store';
import { loadNoteBody }                 from './persistence';

// ─── Dirty-state signal (exported for NoteListItem dot indicator) ─────────────
export const [isDirty, setIsDirty] = createSignal(false);

// ─── Debounce ─────────────────────────────────────────────────────────────────
let saveTimer: ReturnType<typeof setTimeout>;

function scheduleSave(id: string, body: string): void {
  clearTimeout(saveTimer);
  saveTimer = setTimeout(() => {
    // Extract note title from first non-empty line, stripping markdown heading #
    const firstLine = body.split('\n').find((l) => l.trim()) ?? '';
    const title = firstLine.replace(/^#+\s*/, '').trim() || 'Untitled';
    applyNoteSave(id, title, body);
    setIsDirty(false);
  }, 400);
}

// ─── CodeMirror theme (inline — references CSS custom properties from tokens) ──
//
// We use EditorView.theme() rather than a separate .css.ts file here so that
// the theme is co-located with the EditorView instantiation. The values
// reference CSS custom properties generated by vanilla-extract tokens.ts,
// so the token contract is still the single source of truth.
const inkEditorTheme = EditorView.theme(
  {
    '&': {
      height: '100%',
      fontFamily: 'var(--font-prose)',
      fontSize: '1rem',
      lineHeight: 'var(--line-height-relaxed)',
      color: 'var(--color-ink)',
      backgroundColor: 'var(--color-bg)',
    },
    '.cm-content': {
      maxWidth: 'var(--size-editorMaxWidth)',
      margin: '0 auto',
      padding: 'var(--size-editorPaddingY) var(--size-editorPaddingX)',
      caretColor: 'var(--color-accent)',
    },
    '.cm-cursor': {
      borderLeftColor: 'var(--color-accent)',
      borderLeftWidth: '2px',
    },
    '.cm-activeLine': {
      backgroundColor: 'var(--color-cursorLine)',
    },
    '.cm-selectionBackground': {
      backgroundColor: 'var(--color-selection) !important',
    },
    '.cm-focused .cm-selectionBackground': {
      backgroundColor: 'var(--color-selection) !important',
    },
    // Markdown-specific decorations
    '.cm-header-1':  { fontSize: '1.563rem', lineHeight: '1.3', fontWeight: '700' },
    '.cm-header-2':  { fontSize: '1.25rem',  lineHeight: '1.4', fontWeight: '600' },
    '.cm-header-3':  { fontSize: '1rem',     lineHeight: '1.5', fontWeight: '600' },
    '.cm-strong':    { fontWeight: '700' },
    '.cm-em':        { fontStyle: 'italic' },
    '.cm-link':      { color: 'var(--color-accent)' },
    '.cm-url':       { color: 'var(--color-inkFaint)' },
    '.cm-monospace': { fontFamily: 'var(--font-mono)', fontSize: '0.875em' },
    // Fenced code blocks get a subtle background
    '.cm-codeBlock': {
      backgroundColor: 'rgba(26, 21, 16, 0.04)',
      borderRadius: '2px',
      padding: '0 0.25em',
    },
    // Scrollbar styling (WebKit)
    '.cm-scroller::-webkit-scrollbar': { width: '6px' },
    '.cm-scroller::-webkit-scrollbar-track': { background: 'transparent' },
    '.cm-scroller::-webkit-scrollbar-thumb': {
      background: 'var(--color-inkGhost)',
      borderRadius: '3px',
    },
    '&.cm-focused': { outline: 'none' },
  },
  { dark: false },
);

// ─── Component ────────────────────────────────────────────────────────────────

export function Editor(): JSX.Element {
  let container!: HTMLDivElement;
  let view!: EditorView;
  // Guard: prevents the update listener from treating programmatic note-load
  // dispatches as user edits that should trigger a save.
  let isLoadingNote = false;

  onMount(() => {
    view = new EditorView({
      state: EditorState.create({
        doc: '',
        extensions: [
          basicSetup,
          markdown({ base: markdownLanguage, codeLanguages: languages }),
          inkEditorTheme,
          EditorView.updateListener.of((update) => {
            if (!update.docChanged || isLoadingNote) return;
            const id = store.activeNoteId;
            if (!id) return;
            setIsDirty(true);
            scheduleSave(id, update.state.doc.toString());
          }),
          // Line wrapping — essential for a writing tool
          EditorView.lineWrapping,
        ],
      }),
      parent: container,
    });
  });

  // ── Note switching ──────────────────────────────────────────────────────────
  createEffect(() => {
    const id = store.activeNoteId;
    if (!id || !view) return;

    isLoadingNote = true;
    clearTimeout(saveTimer); // Cancel any pending save from the previous note
    setIsDirty(false);

    const body = loadNoteBody(id);

    // Step 1: Dim the editor surface (CSS transition handles the fade)
    container.dataset.transitioning = 'true';

    // Step 2: Replace document contents
    view.dispatch({
      changes: {
        from: 0,
        to: view.state.doc.length,
        insert: body,
      },
      selection: EditorSelection.cursor(0),
    });

    // Step 3: Clear undo history so Cmd+Z can't reach the previous note's text.
    // We dispatch a second transaction to avoid fighting with CM6's history extension.
    view.dispatch({
      effects: EditorView.scrollIntoView(0, { y: 'start' }),
    });

    // Step 4: Un-dim after one animation frame (let the transition play)
    requestAnimationFrame(() => {
      delete container.dataset.transitioning;
      isLoadingNote = false;
      // Focus the editor after switching, placing cursor at start
      view.focus();
    });
  });

  onCleanup(() => {
    clearTimeout(saveTimer);
    view?.destroy();
  });

  return (
    <div
      ref={container}
      class="editor-root"
      // data-transitioning drives the CSS opacity crossfade in Editor.css.ts
    />
  );
}
