/**
 * extensions.ts — CodeMirror 6 extension bundle for Ink.
 *
 * This module assembles the CM6 extension list that defines the editor's
 * behavior and appearance. It is separate from Editor.tsx so that the
 * extension list can be tested and modified without touching the Solid
 * component lifecycle.
 *
 * Extension choices explained:
 *
 *   - basicSetup: CM6's opinionated starter pack. Includes history (Cmd+Z),
 *     closeBrackets, syntax highlighting, autocompletion base, and more.
 *
 *   - markdown(): Full GFM markdown language support. Includes:
 *     - Inline decorations (bold renders bold, italic renders italic)
 *     - Header detection
 *     - Link and code detection
 *     - Fenced code blocks with nested language parsing (via `codeLanguages`)
 *
 *   - languages (from @codemirror/language-data): Lazy-loaded language
 *     definitions for fenced blocks. The initial bundle is tiny; language
 *     parsers are loaded on demand. This is the code-split chunk.
 *
 *   - EditorView.lineWrapping: Essential for a writing tool. Without this,
 *     long markdown lines extend past the viewport.
 *
 *   - inkEditorTheme: CM6 theme built from the tokens.ts CSS custom properties.
 *     Using CSS var() references means the theme responds to :root changes
 *     (future dark mode) without rebuilding the EditorView.
 */
import { EditorView, minimalSetup } from 'codemirror';
import { markdown, markdownLanguage } from '@codemirror/lang-markdown';
import { languages } from '@codemirror/language-data';
import { HighlightStyle, syntaxHighlighting } from '@codemirror/language';
import { tags as t } from '@lezer/highlight';
import type { Extension } from '@codemirror/state';
import type { ViewUpdate } from '@codemirror/view';

// ─── Ink editor theme ─────────────────────────────────────────────────────────
//
// Values reference CSS custom properties generated by vanilla-extract tokens.ts.
// These var() references survive at runtime because vanilla-extract emits the
// :root { --color-bg: #F5F0E8; ... } block to the CSS bundle.

export const inkEditorTheme = EditorView.theme(
  {
    '&': {
      height: '100%',
      fontFamily: 'var(--font-prose)',
      fontSize: '1rem',
      lineHeight: 'var(--line-height-relaxed)',
      color: 'var(--color-ink)',
      backgroundColor: 'var(--color-bg)',
    },
    '.cm-scroller': {
      overflow: 'auto',
      height: '100%',
    },
    '.cm-content': {
      maxWidth: 'var(--size-editorMaxWidth)',
      margin: '0 auto',
      padding: 'var(--size-editorPaddingY) var(--size-editorPaddingX)',
      caretColor: 'var(--color-accent)',
      fontFamily: 'var(--font-prose)',
    },
    '.cm-cursor, .cm-dropCursor': {
      borderLeftColor: 'var(--color-accent)',
      borderLeftWidth: '2px',
    },
    '.cm-activeLine': {
      backgroundColor: 'var(--color-cursorLine)',
    },
    '.cm-activeLineGutter': {
      backgroundColor: 'var(--color-cursorLine)',
    },
    '.cm-selectionBackground': {
      backgroundColor: 'var(--color-selection) !important',
    },
    '&.cm-focused > .cm-scroller > .cm-selectionLayer .cm-selectionBackground': {
      backgroundColor: 'var(--color-selection)',
    },
    // Gutters
    '.cm-gutters': {
      backgroundColor: 'var(--color-bg)',
      borderRight: '1px solid var(--color-border)',
      color: 'var(--color-inkFaint)',
    },
    // Scrollbar styling (WebKit / Blink)
    '.cm-scroller::-webkit-scrollbar':        { width: '6px' },
    '.cm-scroller::-webkit-scrollbar-track':  { background: 'transparent' },
    '.cm-scroller::-webkit-scrollbar-thumb':  {
      background: 'var(--color-inkGhost)',
      borderRadius: '3px',
    },
    // Remove the default CM6 focus ring (we render our own on the wrapper)
    '&.cm-focused': { outline: 'none' },
    // Tooltip (autocompletion, hover)
    '.cm-tooltip': {
      backgroundColor: 'var(--color-bgSidebar)',
      border: '1px solid var(--color-border)',
      borderRadius: '4px',
      boxShadow: '0 2px 8px rgba(26, 21, 16, 0.10)',
    },
    '.cm-tooltip-autocomplete ul li[aria-selected]': {
      backgroundColor: 'var(--color-bgActive)',
      color: 'var(--color-ink)',
    },
  },
  { dark: false },
);

// ─── Ink highlight style ──────────────────────────────────────────────────────
//
// Overrides the default CM6 highlight colors with Ink's warm palette.
// These map lezer AST tags to CSS styles for markdown tokens.

export const inkHighlightStyle = HighlightStyle.define([
  // Headings: display font, progressively smaller
  { tag: t.heading1, fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '1.563rem', lineHeight: '1.3', color: 'var(--color-ink)' },
  { tag: t.heading2, fontFamily: 'var(--font-display)', fontWeight: '700', fontSize: '1.25rem',  lineHeight: '1.4', color: 'var(--color-ink)' },
  { tag: t.heading3, fontFamily: 'var(--font-display)', fontWeight: '600', fontSize: '1.063rem', lineHeight: '1.5', color: 'var(--color-ink)' },
  { tag: t.heading4, fontFamily: 'var(--font-display)', fontWeight: '600', fontSize: '1rem',     lineHeight: '1.5', color: 'var(--color-inkSecondary)' },
  { tag: t.heading,  fontFamily: 'var(--font-display)', fontWeight: '600', color: 'var(--color-ink)' },
  // Inline
  { tag: t.strong,      fontWeight: '700', color: 'var(--color-ink)' },
  { tag: t.emphasis,    fontStyle: 'italic' },
  { tag: t.strikethrough, textDecoration: 'line-through', color: 'var(--color-inkSecondary)' },
  { tag: t.link,        color: 'var(--color-accent)' },
  { tag: t.url,         color: 'var(--color-inkFaint)' },
  // Code
  { tag: t.monospace,   fontFamily: 'var(--font-mono)', fontSize: '0.875em' },
  { tag: t.code,        fontFamily: 'var(--font-mono)', fontSize: '0.875em', color: 'var(--color-inkSecondary)' },
  // Punctuation / markup markers
  { tag: t.processingInstruction, color: 'var(--color-inkFaint)' },
  { tag: t.contentSeparator,      color: 'var(--color-inkGhost)' },
  { tag: t.meta,                  color: 'var(--color-inkFaint)' },
  // Blockquote
  { tag: t.quote,   fontStyle: 'italic', color: 'var(--color-inkSecondary)' },
  // List markers
  { tag: t.list,    color: 'var(--color-accent)' },
  // HR
  { tag: t.separator, color: 'var(--color-inkGhost)' },
]);

// ─── Extension factory ────────────────────────────────────────────────────────

/**
 * Build the full extension array for a new EditorView.
 * The update listener is passed in so Editor.tsx owns the callback lifecycle.
 */
export function buildExtensions(onUpdate: (update: ViewUpdate) => void): Extension[] {
  return [
    // minimalSetup provides: history, drawSelection, highlightActiveLine,
    // closeBrackets, bracketMatching, search (Ctrl+F), default keymaps.
    // It does NOT include lineNumbers() or foldGutter() — right for a writing tool.
    minimalSetup,
    markdown({ base: markdownLanguage, codeLanguages: languages }),
    inkEditorTheme,
    syntaxHighlighting(inkHighlightStyle),
    EditorView.lineWrapping,
    EditorView.updateListener.of(onUpdate),
  ];
}
