/**
 * editor.css.ts — styles for the CodeMirror editor wrapper
 *
 * The CodeMirror theme itself is defined inline in Editor.tsx via EditorView.theme()
 * so it can reference CSS custom properties generated by tokens.css.ts.
 * This file handles only the wrapper container and transition states.
 */
import { style } from '@vanilla-extract/css';
import { tokens } from '../design/tokens.css';

export const editorRoot = style({
  height: '100%',
  width: '100%',
  transition: `opacity ${tokens.motion.durationFast} ${tokens.motion.easeOut}`,
  // opacity transition is triggered by data-transitioning attribute added in Editor.tsx
  selectors: {
    '&[data-transitioning]': {
      opacity: 0.55,
      pointerEvents: 'none',
    },
  },
});

export const editorPlaceholder = style({
  display: 'flex',
  flexDirection: 'column',
  alignItems: 'center',
  justifyContent: 'center',
  height: '100%',
  gap: tokens.space['3'],
  color: tokens.color.inkFaint,
  userSelect: 'none',
  fontFamily: tokens.font.ui,
  fontSize: tokens.fontSize.sm,
});
