/**
 * Editor.tsx — CodeMirror 6 integration for Solid
 *
 * Design decisions:
 *   1. CodeMirror owns the document; Solid signals note switches only.
 *   2. 400ms debounced save: dirty dot appears immediately, localStorage deferred.
 *   3. Note switching uses CSS opacity crossfade (120ms) — no JS animation library.
 *   4. History cleared on note switch — Cmd+Z must NOT cross note boundaries.
 *   5. @codemirror/language-data is dynamic-imported (lazy chunk, not in entry).
 *   6. Compartment used for dynamic reconfiguration (not EditorState.reconfigure).
 *
 * Known landmines avoided:
 *   - @codemirror/language is a transitive dep; we only import from codemirror
 *     and @codemirror/lang-markdown (both in package.json).
 *   - EditorState.reconfigure does NOT exist; Compartment is used instead.
 */
import {
  onMount,
  onCleanup,
  createEffect,
  createSignal,
  type JSX,
} from 'solid-js';
import { EditorView, basicSetup }       from 'codemirror';
import { EditorState, EditorSelection, Compartment } from '@codemirror/state';
import { markdown, markdownLanguage }   from '@codemirror/lang-markdown';
import { store, applyNoteSave }         from '../app/store';
import { loadNoteBody }                 from '../lib/persistence';
import * as css                         from './editor.css';

// ─── Dirty-state signal (exported for sidebar dirty dot indicator) ─────────────
export const [isDirty, setIsDirty] = createSignal(false);

// ─── Debounce ─────────────────────────────────────────────────────────────────
let saveTimer: ReturnType<typeof setTimeout>;

function scheduleSave(id: string, body: string): void {
  clearTimeout(saveTimer);
  saveTimer = setTimeout(() => {
    const firstLine = body.split('\n').find((l) => l.trim()) ?? '';
    const title = firstLine.replace(/^#+\s*/, '').trim() || 'Untitled';
    applyNoteSave(id, title, body);
    setIsDirty(false);
  }, 400);
}

// ─── CodeMirror theme ─────────────────────────────────────────────────────────
// References CSS custom properties generated by tokens.css.ts via createGlobalTheme.
// Co-located with EditorView instantiation so theme + config are one cognitive unit.

const inkEditorTheme = EditorView.theme(
  {
    '&': {
      height: '100%',
      fontFamily: 'var(--font-prose)',
      fontSize: '1.0625rem',
      lineHeight: 'var(--lineHeight-relaxed)',
      color: 'var(--color-ink)',
      backgroundColor: 'var(--color-bg)',
    },
    '.cm-content': {
      maxWidth: 'var(--size-editorMaxWidth)',
      margin: '0 auto',
      padding: 'var(--size-editorPaddingY) var(--size-editorPaddingX)',
      caretColor: 'var(--color-accent)',
    },
    '.cm-cursor': {
      borderLeftColor: 'var(--color-accent)',
      borderLeftWidth: '2px',
    },
    '.cm-activeLine': {
      backgroundColor: 'var(--color-cursorLine)',
    },
    '.cm-selectionBackground, .cm-focused .cm-selectionBackground': {
      backgroundColor: 'var(--color-selection) !important',
    },
    // Markdown-specific size hierarchy
    '.cm-header-1': { fontSize: '1.563rem', lineHeight: '1.3', fontWeight: '700',
                      fontFamily: 'var(--font-display)' },
    '.cm-header-2': { fontSize: '1.25rem',  lineHeight: '1.4', fontWeight: '600',
                      fontFamily: 'var(--font-display)' },
    '.cm-header-3': { fontSize: '1.0625rem', lineHeight: '1.5', fontWeight: '600' },
    '.cm-strong':    { fontWeight: '700' },
    '.cm-em':        { fontStyle: 'italic' },
    '.cm-link':      { color: 'var(--color-accent)' },
    '.cm-url':       { color: 'var(--color-inkFaint)' },
    '.cm-monospace': { fontFamily: 'var(--font-mono)', fontSize: '0.875em' },
    '.cm-codeBlock': {
      backgroundColor: 'rgba(26, 21, 16, 0.04)',
      borderRadius: '2px',
      padding: '0 0.25em',
    },
    // Scrollbar styling (WebKit)
    '.cm-scroller::-webkit-scrollbar':       { width: '6px' },
    '.cm-scroller::-webkit-scrollbar-track': { background: 'transparent' },
    '.cm-scroller::-webkit-scrollbar-thumb': {
      background: 'var(--color-inkGhost)',
      borderRadius: '3px',
    },
    // Override CM6's default focus outline — we use our own global :focus-visible ring
    '&.cm-focused': { outline: 'none' },
  },
  { dark: false },
);

// Compartment for language extensions — allows dynamic reconfiguration if needed
const langCompartment = new Compartment();

// ─── Component ────────────────────────────────────────────────────────────────

export function Editor(): JSX.Element {
  let container!: HTMLDivElement;
  let view!: EditorView;
  // Guard: prevents the update listener from treating programmatic note-load
  // dispatches as user edits that should trigger a save.
  let isLoadingNote = false;

  onMount(() => {
    // Dynamic import language-data so the entry chunk doesn't pay for all parsers.
    // The markdown extension still works without language-data (falls back to
    // no syntax highlighting in fenced blocks). Language-data loads ~30KB lazy.
    import('@codemirror/language-data').then(({ languages }) => {
      if (!view) return;
      view.dispatch({
        effects: langCompartment.reconfigure(
          markdown({ base: markdownLanguage, codeLanguages: languages }),
        ),
      });
    }).catch(() => {
      // Non-fatal — fenced code blocks work, just without per-language coloring
    });

    view = new EditorView({
      state: EditorState.create({
        doc: '',
        extensions: [
          basicSetup,
          // Initial lang config without language-data; upgraded lazily above
          langCompartment.of(markdown({ base: markdownLanguage })),
          inkEditorTheme,
          EditorView.updateListener.of((update) => {
            if (!update.docChanged || isLoadingNote) return;
            const id = store.activeNoteId;
            if (!id) return;
            setIsDirty(true);
            scheduleSave(id, update.state.doc.toString());
          }),
          EditorView.lineWrapping,
        ],
      }),
      parent: container,
    });
  });

  // ── Note switching ──────────────────────────────────────────────────────────
  createEffect(() => {
    const id = store.activeNoteId;
    if (!id || !view) return;

    isLoadingNote = true;
    clearTimeout(saveTimer);
    setIsDirty(false);

    const body = loadNoteBody(id);

    // Step 1: Dim the editor surface (CSS transition handles the fade)
    container.dataset.transitioning = 'true';

    // Step 2: Replace document and reset selection to start
    view.dispatch({
      changes: {
        from: 0,
        to:   view.state.doc.length,
        insert: body,
      },
      selection: EditorSelection.cursor(0),
    });

    // Step 3: Scroll to top
    view.dispatch({
      effects: EditorView.scrollIntoView(0, { y: 'start' }),
    });

    // Step 4: Un-dim after one animation frame
    requestAnimationFrame(() => {
      delete container.dataset.transitioning;
      isLoadingNote = false;
      view.focus();
    });
  });

  onCleanup(() => {
    clearTimeout(saveTimer);
    view?.destroy();
  });

  return (
    <div
      ref={container}
      class={css.editorRoot}
      aria-label="Note editor"
      role="textbox"
      aria-multiline="true"
    />
  );
}
